### PR TITLE
Bounty payout voting and payment execution - self-evolving AI-DAO #5986

### PR DESCRIPTION
**Pull request by StevenL98**
This is the final result for the Blockchain project of team [#5986](https://github.com/Tribler/tribler/issues/5986). 
For more information see the corresponding issue.
The updated readmes are on their way.

### CODE REVIEW

**Comment by RFHuisman** [comment]
@xoriole we rebased the commit history and fixed a gradle dependency error from com.mattskala:itemadapter:0.4 project-wide. Locally, the tests are passing, but there is still an issue with dependency com.goterl.lazycode:lazysodium-android:4.1.0 on the CI (you can check the logs). I don't think that this has to do with our PR. Anyways, we wanted to let you know that our code is now ready to be merged/reviewed

**Comment by xoriole** [comment]
@RFHuisman Thanks for the update. Instead of using itemadapter library as file dependency, can you try using this jitpack dependency?
https://jitpack.io/#MattSkala/recyclerview-itemadapter/0.4

For lazysodium, it seems the package has changed, new packages are:
- `com.goterl:lazysodium-java:VERSION_NUMBER`  [here](https://github.com/terl/lazysodium-java)
- `com.goterl:lazysodium-android:VERSION_NUMBER@aar` [here](https://github.com/terl/lazysodium-android)

Note that repo is `mavenCentral`. Bintray is not available anymore.

**Comment by xoriole** [comment]
@RFHuisman @StevenL98 Could you please rebase the PR to master? The dependency issues should be fixed after rebase.

**Comment by RFHuisman** [comment]
@xoriole it should be fine now 👍

**Comment by RFHuisman** [comment]
@xoriole documentation has been added now as well in the readme's

**Comment by xoriole** [comment]
@RFHuisman Based on the meeting today, final tasks to finish:
1. Add the code for server-side faucet within a subdirectory with proper readme documentation on how to set up the server.
2. Update the luxury communism documentation to link the setup doc for the server.
3. Test that the latest code works with the server and build a working APK or app bundle

**Comment by RFHuisman** [comment]
@xoriole we removed all commented code from the codebase and updated the currencyii readme to link to our repository with the serverside code. This repository contains documentation on how to setup and maintain the regtest server.

**Comment by StevenL98** [comment]
The final .apk file can be downloaded [here!](https://we.tl/t-gab5lfveGK)
Note, it will expire in 1 week (31-05-2021)

**Pull request merged**
