### PR TITLE
Introduce the Peer AI module

### PR DESCRIPTION
**Pull request by kandrio**
This PR introduces the Peer AI module of the superapp. All work around Peer AI made by @quintene

### CODE REVIEW

**Comment by kandrio** [comment]
There's a test error that I don't understand currently. Working on it to resolve it

**Comment by InvictusRMC** [comment]
> /home/runner/work/trustchain-superapp/trustchain-superapp/app/src/main/AndroidManifest.xml: Error: When targeting Android 13 or higher, posting a permission requires holding the POST_NOTIFICATIONS permission (usage from com.bumptech.glide.request.target.NotificationTarget) [NotificationPermission]

Seems to be a permission error. See [StackOverflow](https://stackoverflow.com/questions/73940694/android-13-not-asking-for-post-notifications-permission).

**Comment by kandrio** [comment]
@InvictusRMC I carefully took a look at the permissions that PeerAI was requesting and I found `READ_INTERNAL_STORAGE` in this line:
- https://github.com/quintene/trustchain-superapp/blob/37312bd4187fba929cf2af31375b426fcbfc0629/peerai/src/main/AndroidManifest.xml#L5

However, after taking a look at the official Android [documentation](https://developer.android.com/reference/android/Manifest.permission), I saw that there is no such permission as `READ_INTERNAL_STORAGE`. So I removed it in a small commit and the weird error went away. PeerAI seems to be working just fine.

Maybe @quintene could shed some light here too, but other than that, it seems like we're good to merge

**Comment by kandrio** [comment]
@InvictusRMC Should we merge this?

**Pull request merged**
