### PR TITLE
Currency I: First Implementation of Machine Learning Trader App

### PR DESCRIPTION
**Pull request by mvanmeerten**
Issue [#5143](https://github.com/Tribler/tribler/issues/5143)
- [x] Integrated AI technology (naive bayes classifier)
 - [x] Observe the live market IPv8 community
- [x] Create your own test bid/ask workload (Kotlin)
 - [x] No trustchain block creation, simple message broadcasting only to few dozen peers (will not scale, inefficient)
- [x] No special matchmaking agents, just match incoming ask with your own bid (or vise versa)
- [x] Create bid/ask in the market community manually in GUI (helpful for testing)
 - [x] Display orderbook on the screen (build on Freedom of Computing team)
 - [x] Integrate transfer of cybercurrency QR-code one-shot operation
- [x] Trading agent buy for this price, sell for this price
 - [x] Turn on/off on screen
 - [ ] give trade advice
 - [X] turn on to do simplistic automatic trading
- [ ] Testnet Bitcoins versus your own currency trading pair (e.g. Dymbedollars)

### CODE REVIEW

**Comment by MattSkala** [comment]
I see you have probably accidentally commited some *.log files, can you please remove them to keep the repo clean?

**Comment by MattSkala** [comment]
I see there are some compiler warnings, as well as minor ktlint issues. You should see them after running  `./gradlew check --no-build-cache`. Can you please fix those? You can fix most formatting issues automatically by running `./gradlew ktlintFormat`.

I would recommend you to treat compiler and lint warnings as errors by setting `android.kotlinOptions.allWarningsAsErrors = true` and `ktlint.ignoreFailures = false` in your `build.gradle`, [in the same way as I did for the common module](https://github.com/Tribler/trustchain-superapp/commit/5915ca2c8195754aa881b4a3efae5a7db10db1e0). In that way, they will not go unnoticed by the CI check that should now run automatically for every pull request.

**Comment by martijnbosma** [comment]
Removed all *.log files and ran` ./gradlew ktlintFormat`. Added `android.kotlinOptions.allWarningsAsErrors = true` and `ktlint.ignoreFailures = false` in all the build.gradle files.

**Comment by MattSkala** [comment]
There are some merge conflicts because of conflicting changes with previously merged PRs by other teams. Please rebase to the latest `dao` branch and resolve the conflicts.

**Comment by erwinvanthiel** [comment]
The pull request seems to lack unit tests, or did I overlook them?

**Comment by MattSkala** [comment]
There is some issue with cloning the `kotlin-ipv8` submodule, can you please check? Make sure it points to the latest commit in `Tribler/kotlin-ipv8#master`.

**Comment by martijnbosma** [comment]
@MattSkala Could you check why the error -
```
> Task :ipv8:compileTestKotlin FAILED
e: warnings found and -Werror specified
w: /Users/runner/runners/2.168.0/work/trustchain-superapp/trustchain-superapp/kotlin-ipv8/ipv8/src/test/java/nl/tudelft/ipv8/BaseCommunityTest.kt: (21, 2): 'UseExperimental' is deprecated. Please use OptIn instead.
w: /Users/runner/runners/2.168.0/work/trustchain-superapp/trustchain-superapp/kotlin-ipv8/ipv8/src/test/java/nl/tudelft/ipv8/attestation/trustchain/TrustChainCrawlerTest.kt: (19, 2): 'UseExperimental' is deprecated. Please use OptIn instead. 
```
- is appearing? I don't think we changed any of that code.

**Comment by MattSkala** [comment]
@martijnbosma You updated Kotlin to 1.3.71, in which UseExperimental annotation is deprecated. I'll update kotlin-ipv8 to the latest Kotlin version eventually, but for now if you downgrade to the original version (1.3.61), the warning should disappear.

**Pull request merged**
