### PR TITLE
Add Crashlytics

### PR DESCRIPTION
**Pull request by MattSkala**
Crashlytics SDK is now bundled with the release build type (which is now being built by Github Actions) to receive automated crash reports.

### CODE REVIEW

**Comment by synctext** [comment]
posting a direct link to the APK.zip to bypass Android security obstructions (includes the great crashanalytics stuff).
[app (4).zip](https://github.com/Tribler/trustchain-superapp/files/4569832/app.4.zip)

**Comment by synctext** [comment]
Sadly not seeing any crash reporting. Had several 'exits to home screen' without any error. Both reset to main superapp screen and exit to Android OS. All silent!

**Comment by MattSkala** [comment]
@synctext Thanks for testing it. Crashlytics logs crashes remotely, they are only available to the developers in the [Firebase Console](https://console.firebase.google.com/). I have invited you to the project.

Here is the stack trace I received from Huawei: https://github.com/Tribler/trustchain-superapp/pull/30 It looks like it could be caused by the version of Java used for building, please try this build: https://github.com/Tribler/trustchain-superapp/suites/649114572/artifacts/5543504

**Comment by synctext** [comment]
You fixed it!
silent reporting to central Google service:-)
Can you indicate the build number in the debug screen possibly? Do an official release for first testing round?

**Pull request merged**
