### PR TITLE
Literature Dao

### PR DESCRIPTION
**Pull request by keonchennl**

### CODE REVIEW

**Comment by sisko444** [comment]
Please refer to the [issue ](https://github.com/Tribler/tribler/issues/6783)this PR originates from.
We have implemented the requested functionality to the best of our capacity.
The final post on the issue is an accurate portrayal of the current state of the project.

**Comment by InvictusRMC** [comment]
Hi team, please ensure your code passes our CI.

**Comment by keonchennl** [comment]
> Hi team, please ensure your code passes our CI.

The pipeline fails on master because of the info.blockchain.api library. And [this repository we used for this library](https://github.com/blockchain/api-v1-client-java) got removed. How could we continue on this?

**Comment by InvictusRMC** [comment]
Hi @keonchennl, can you fix the lint issues?

**Pull request closed without merging**
