### PR TITLE
Federated music recommendation

### PR DESCRIPTION
**Pull request by JCBrouwer**
Add federated, privacy-preserving music recommendations to MusicDAO.

Two recommendation models are added: one based on collaborative filtering, the other based on musical features (calculated with Essentia, which is added as a submodule). The weights of the model are gossiped between users and finetuned locally based on user playcounts of songs in the app. To save duplicate work, musical features calculated by Essentia are gossiped as well. User playcounts never leave their device, only song features and global model weights are shared.

The MusicDAO interface now has two album covers at the top of the interface where recommendations are shown. Refreshing will generate new recommendations.

See [this issue](https://github.com/Tribler/tribler/issues/5987) for more information.

A follow-up pull request will contain more documentation, an updated README, and more docstrings for the code not yet commented.

### CODE REVIEW

**Review by xoriole — COMMENTED** [review]
Wow! this PR is huge. A single commit (out of 3) with 65k lines is too big. Looking at the commit message, it looks like a squashed message. 

It'll be easier to review if the changes can be broken down into several meaningful commits.

**Comment by JCBrouwer** [comment]
Hello @xoriole, sorry about the ridiculous number of lines. ~60k of them were low-level Essentia feature statistics that we were using to test our SVM's performance. I've moved those assets to the superapp-essentia submodule for clarity.

We squashed our main changes into one commit as we had about 160 commits over the course of development. Most of the changes are strongly interlinked, so it's pretty hard / a lot of redevelopment to break them up.

Is the PR reviewable as it stands now (~4000 lines changed)? Or should we try and break it up further?

**Review by xoriole — CHANGES_REQUESTED** [review]
Could you remove `app-debug.apk` binary from this PR?

**Review by xoriole — APPROVED** [review]

**Comment by JCBrouwer** [comment]
I've just gone through and fixed the merge conflicts @xoriole , but now there seem to be errors related to dependencies from dl.bintray.com 403ing

It looks like it has something to do with the sunset of that service that's happening next week: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

What should we do about these broken dependencies?

**Comment by JCBrouwer** [comment]
Ahh nice, looks like it's working now, maybe there was just some temporary downtime at bintray.

Can this be merged?

**Comment by xoriole** [comment]
@JCBrouwer That's good then

**Pull request merged**
