### PR TITLE
MusicDAO first prototype

### PR DESCRIPTION
**Pull request by Tim-W**
First pull request for this project: https://github.com/Tribler/tribler/issues/5134

This is a first experimental iteration. Many things should be improved in the future regarding stability of playback, streaming and buffering.

**MusicDAO**
In short, the MusicDAO  is an IPv8 app where users can share and discover tracks on the trustchain. Track streaming, downloading, and seeking interactions are done using JLibtorrent. 

A user can publish a Release (which is an album/EP/single/...), after which the app creates a magnet link referring to these audio tracks. Then, the app creates a proposal block for the trustchain which contains some metadata (release date, title, ...) this metadata is submitted by the user with a dialog. When a signed block is discovered (currently are self-signed), the app tries to obtain the file list using JLibtorrent. Each file can be streamed independently on clicking the play button. 

**Screens**

**Videos**
Video 1: Load Example. https://drive.google.com/open?id=1xbcm2jbuEn5baqISQ6OBNcwAtp3vQiP3 This uses a default magnet link for an album that has a decent amount of peers. The user submits the metadata and the block gets proposed and signed. Then playback.
Video 2: Share Track. https://drive.google.com/open?id=1nXFSWxaXE6hzuKHocksaL3lLNjO_j0lq Note: as a fresh magnet link is generated in this video, there is only 1 peer. For this reason it will be difficult to obtain the metadata of the magnet link (cold start issue, write about this in thesis) so the video stops there. 

[app-debug.apk.zip](https://github.com/Tribler/trustchain-superapp/files/4615745/app-debug.apk.zip)

### CODE REVIEW

**Comment by MattSkala** [comment]
It looks like dependencies are clashing because the project now includes two different versions of jlibtorrent. I think you'll have to make sure the same version is used by TorrentStream-Android and FOC module. I see the latest master of TorrentStream-Android already uses jlibtorrent 1.2.5.0, but it's not released yet, so you could include it as a Git submodule and depend on its implementation.

Then you'll probably have to use Gradle exclude mechanism to exclude duplicate classes from one of the modules: https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.DependencyHandler.html

**Comment by MattSkala** [comment]
Also please change your base branch from dao to master, as dao is merged already.

**Comment by synctext** [comment]
from FOC inclusion I think we don't need (unstable) bleeding edge code. Feel free to decide which version of Libtorrent to include or magically use both.

**Comment by Tim-W** [comment]
Thanks for the help. Seems like I fixed it by excluding jlibtorrent from the torrenstream library:
https://github.com/Tribler/trustchain-superapp/pull/34/commits/bab808a4ee3e85c62b0db805d15eecabf4bc2918#diff-94823040893f0a90f5e442b6539bfa78R65

**Comment by Tim-W** [comment]
@synctext @MattSkala Ready for review. 
Also I added documentation to README.md and added 2 videos and 3 screenshots. Pls see the text on the pull request.

@MattSkala thanks for the help with Jlibtorrent. fixed it now

**Comment by MattSkala** [comment]
Thanks for the pull request.

Can you please add ktlint plugin to your module to enforce consistent code style? It should be enough to add `apply plugin: 'org.jlleitschuh.gradle.ktlint'` at the top of your `build.gradle` and configure using `ktlint` block in the same way as in other modules.

I see there are some compiler warnings. You should see them after running `./gradlew check --no-build-cache`. Can you please fix those? I would recommend you to treat compiler warnings as errors by setting `android.kotlinOptions.allWarningsAsErrors = true` in your build.gradle, in the same way as in other modules. In that way, they will not go unnoticed by the CI check that should now run automatically for every pull request.

**Comment by synctext** [comment]
Installed .apk linked above: [app-debug.apk.zip](https://github.com/Tribler/trustchain-superapp/files/4615745/app-debug.apk.zip)
That crashed a few times. @MattSkala should have error reports from his central Google reporting server now, build 1100.
But saw fascinating fast updates of bandwidth stats and DHT details from Libtorrent! Does not seem to have "autoplay" when it has 100% of file downloaded. btw I could not understand the exact role of the 2 play buttons: one below progress bar and before the track name (understand this is an early release and lack of time for polish).

**Comment by Tim-W** [comment]
@synctext Thanks for trying it out. Yes there is still quite some work to do to make streaming and error handling, autoplay, seeking more stable. That will take more days with debugging and testing unfortunately. 
In terms of the 2 buttons, see the description for these videos in the PR description:

Video 1: Load Example. This uses a default magnet link for an album that has a decent amount of peers. The user submits the metadata and the block gets proposed and signed. Then playback.
Video 2: Share Track. Note: as a fresh magnet link is generated in this video, there is only 1 peer. For this reason it will be difficult to obtain the metadata of the magnet link (cold start issue, write about this in thesis) so the video stops there.

@MattSkala Thanks for the feedback, I'll try to fix the warnings etc

**Comment by Tim-W** [comment]
A test is failing in the build but I don't think it has anything to do with the code from musicdao.  @MattSkala any idea what goes wrong here? Can the build be manually restarted?

```

nl.tudelft.ipv8.messaging.tftp.TFTPEndpointTest > send FAILED
    java.lang.AssertionError at TFTPEndpointTest.kt:28

150 tests completed, 1 failed

> Task :ipv8:test FAILED
> Task :freedomOfComputing:generateReleaseUnitTestStubRFile
> Task :freedomOfComputing:generateDebugUnitTestStubRFile
448 actionable tasks: 448 executed
```

**Comment by MattSkala** [comment]
That was my flaky test that I should fix, it passed after restart.

I was just quickly testing the app and it crashes when you open Music DAO, leave, and open it again:

```
2020-05-13 14:58:52.722 5307-5307/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: nl.tudelft.trustchain, PID: 5307
    java.lang.RuntimeException: Unable to start activity ComponentInfo{nl.tudelft.trustchain/com.example.musicdao.MusicService}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5150)
        at android.view.ViewGroup.addView(ViewGroup.java:4979)
        at android.view.ViewGroup.addView(ViewGroup.java:4919)
        at com.example.musicdao.MusicService.onCreate(MusicService.kt:56)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
```

**Pull request merged**
